import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer, Header } from '@/components/layout';
import { FavoriteProvider } from '@/contexts/FavoriteContext';
import { MovieProvider } from '@/contexts/MovieContext';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Movie Explorer App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/favicon/favicon.ico' />
        <link rel='icon' href='/favicon/favicon-16x16.png' sizes='16x16' />
        <link rel='icon' href='/favicon/favicon-32x32.png' sizes='32x32' />
        <link rel='apple-touch-icon' href='/favicon/apple-touch-icon.png' sizes='180x180' />
        <meta name='theme-color' content='#ffffff' />
      </head>
      <body
        className={`${inter.variable} font-inter bg-black suppressHydrationWarning`}
      >
        <MovieProvider>
          <FavoriteProvider>
            <Header />
            {children}
            <Footer />
          </FavoriteProvider>
        </MovieProvider>
      </body>
    </html>
  );
}
