import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer, Header } from '@/components/layout';
import { FavoriteProvider } from '@/contexts/FavoriteContext';
import { MovieProvider } from '@/contexts/MovieContext';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} font-inter bg-black suppressHydrationWarning`}
      >
        <MovieProvider>
          <FavoriteProvider>
            <Header />
            {children}
            <Footer />
          </FavoriteProvider>
        </MovieProvider>
      </body>
    </html>
  );
}
